version: "3.7"

services:
  postgresql:
    image: postgres:16.1
    ports:
      - 5432:5432
    volumes:
      - workflow-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=camunda
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U $${POSTGRES_USER}
      interval: 5s
      timeout: 5s
      retries: 5

  camunda:
    image: philipz/workflow-backend:7.20
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  frontedn:
    image: philipz/workflow-frontend:20-alpine
    ports:
      - 3000:3000
    depends_on:
      - camunda

volumes:
  workflow-postgresql-data: