version: "3.7"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - workflow-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: camunda
    healthcheck:
      test: ["CMD", "echo" , ">/dev/tcp/localhost/3306"]
      interval: 5s
      timeout: 5s
      retries: 5

  camunda:
    image: philipz/workflow-backend:7.20
    ports:
      - 8080:8080
    depends_on:
      - mysql

  frontedn:
    image: philipz/workflow-frontend:20-alpine
    ports:
      - 3000:3000
    depends_on:
      - camunda

volumes:
  workflow-mysql-data: