apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-deployment
  namespace: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
        - name: camunda
          image: philipz/workflow-backend:7.20-redis

---
apiVersion: v1
kind: Service
metadata:
  name: camunda-service
  namespace: camunda
spec:
  selector:
    app: camunda
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080