apiVersion: v1
kind: Namespace
metadata:
  name: camunda
  labels:
    eventing.knative.dev/injection: enabled

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: camunda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.1
          env:
            - name: POSTGRES_DB
              value: camunda
            - name: POSTGRES_PASSWORD
              value: password
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pvc
      volumes:
        - name: postgres-pvc
          hostPath:
            path: /home/kind/workflow

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: camunda
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
