camunda.bpm.admin-user:
  id: admin
  password: admin
#server.servlet.context-path: /operate
spring.datasource:
  url: jdbc:mysql://mysql:3306/camunda?characterEncoding=UTF-8&useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: password
