camunda.bpm.admin-user:
  id: admin
  password: admin
#server.servlet.context-path: /operate
spring.datasource:
  url: jdbc:postgresql://postgresql:5432/camunda
  driver-class-name: org.postgresql.Driver
  username: postgres
  password: password
